### ISSUE TITLE
Error with huggingfacehub

### ISSUE THREAD

**Issue by jurassicjordan** [thu-ml/CRM#33]
```gradio app.py
Watching: '/home/jordancruz/Tools/CRM' '/home/jordancruz/Tools/CRM'

Traceback (most recent call last):
  File "/home/jordancruz/Tools/CRM/app.py", line 9, in <module>
    from pipelines import TwoStagePipeline
  File "/home/jordancruz/Tools/CRM/pipelines.py", line 2, in <module>
    from libs.base_utils import do_resize_content
  File "/home/jordancruz/Tools/CRM/libs/base_utils.py", line 23, in <module>
    from diffusers.training_utils import EMAModel
  File "/home/jordancruz/anaconda3/envs/CRM3D/lib/python3.8/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/jordancruz/anaconda3/envs/CRM3D/lib/python3.8/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/jordancruz/anaconda3/envs/CRM3D/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/jordancruz/anaconda3/envs/CRM3D/lib/python3.8/site-packages/huggingface_hub/__init__.py)```

**Comment by AlwynHD** [comment]
This should help you resolve your error:

https://github.com/easydiffusion/easydiffusion/issues/1851
