### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by qiuxin610** [thu-ml/CRM#4]
CRM.pth: 100%|███████████████████████████████████████████████████████████████████████| 476M/476M [13:35<00:00, 583kB/s]
Traceback (most recent call last):
  File "E:\project\CRM\app.py", line 129, in <module>
    model = CRM(specs).to(args.device)
  File "E:\project\CRM\model\crm\model.py", line 59, in __init__
    self.renderer = Renderer(tet_grid_size=self.tet_grid_size, camera_angle_num=self.camera_angle_num,
  File "E:\project\CRM\util\renderer.py", line 15, in __init__
    self.glctx = dr.RasterizeCudaContext()
  File "E:\project\CRM\python\lib\site-packages\nvdiffrast\torch\ops.py", line 177, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "E:\project\CRM\python\lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "E:\project\CRM\python\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "E:\project\CRM\python\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\project\CRM\python\lib\site-packages\torch\utils\cpp_extension.py", line 1793, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "E:\project\CRM\python\lib\site-packages\torch\utils\cpp_extension.py", line 1842, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
E:\project\CRM>python\python.exe -m pip install Ninja
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: Ninja in e:\project\crm\python\lib\site-packages (1.11.1.1)

**Comment by thuwzy** [comment]
What is the version of your python, pytorch and cuda? It seems to be related with the cuda version.

**Comment by qiuxin610** [comment]
python  3.9.12       torch   2.2.0+cu121   cuda 12.3

**Comment by thuwzy** [comment]
My testing environment is torch==1.13.0+cu117. You can try torch 1.x?

**Comment by qiuxin610** [comment]
ok  The problem is solved. I found a winodws ninja.exe that can run in 2.2.0+cu121.
