### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by poem1209** [thu-ml/CRM#5]
请问pytorch的版本具体是什么，使用torch 2.0.1报错torch缺少compiler。
```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.0+cu121 with CUDA 1201 (you have 2.0.1+cu117)
    Python  3.10.11 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\diffusers\utils\import_utils.py", line 684, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "E:\ProgramData\anaconda3\envs\CRM\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\diffusers\models\unet_2d.py", line 24, in <module>
    from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 23, in <module>
    from .attention import AdaGroupNorm
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\diffusers\models\attention.py", line 22, in <module>
    from .attention_processor import Attention
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\diffusers\models\attention_processor.py", line 31, in <module>
    import xformers
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\xformers\__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\xformers\checkpoint.py", line 437, in <module>
    class SelectiveCheckpointWrapper(ActivationWrapper):
  File "E:\ProgramData\anaconda3\envs\CRM\lib\site-packages\xformers\checkpoint.py", line 449, in SelectiveCheckpointWrapper
    @torch.compiler.disable
AttributeError: module 'torch' has no attribute 'compiler'
```

**Comment by poem1209** [comment]
这是我们本地的版本，运行时报上述错误
```
ruff                           0.3.2
safetensors                    0.4.2
scikit-image                   0.22.0
scipy                          1.12.0
semantic-version               2.10.0
setuptools                     68.2.2
shellingham                    1.5.4
six                            1.16.0
sniffio                        1.3.1
starlette                      0.36.3
sympy                          1.12
tifffile                       2024.2.12
tokenizers                     0.13.3
tomlkit                        0.12.0
toolz                          0.12.1
torch                          2.0.1+cu117
torchaudio                     0.13.1+cu117
torchvision                    0.17.0
tqdm                           4.66.2
transformers                   4.27.1
trimesh                        4.2.0
typer                          0.9.0
typing_extensions              4.10.0
typing-inspect                 0.9.0
tzdata                         2024.1
urllib3                        2.2.1
uvicorn                        0.28.0
varname                        0.13.0
wcwidth                        0.2.13
websockets                     11.0.3
wheel                          0.41.2
wrapt                          1.16.0
xatlas                         0.0.9
xformers                       0.0.24
zipp                           3.17.0
```
