### ISSUE TITLE
checkpoint loading size mismatch

### ISSUE THREAD

**Issue by tiangexiang** [thu-ml/CRM#7]
Thanks for your awesome work and contribution!
I tried to run your codes locally after downloading model checkpoints from huggingface, but I encountered a size mismatch error when doing so:

```
Traceback (most recent call last):
  File "/CRM/local_inference.py", line 152, in <module>    
    pipeline = TwoStagePipeline(  
  File "/CRM/pipelines.py", line 31, in __init__
    self.stage1_model.load_state_dict(torch.load(stage1_model_config.resume, map_location="cpu"), strict=False)
  File "/envs/crm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusionInterface:
        size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
```
        
Interestingly, when I swap the checkpoints for ccm_diffusion and pixel_diffusion, both loading and inference work pretty well. But the results are definitely not correct after swapping the checkpoints. 

I have not changed anything to the codes.

**Comment by thuwzy** [comment]
Can you provide the full code of `local_inference.py`?

**Comment by tiangexiang** [comment]
```
import argparse
import numpy as np
import gradio as gr
from omegaconf import OmegaConf
import torch
from PIL import Image
import PIL
from pipelines import TwoStagePipeline
from huggingface_hub import hf_hub_download
import os
import rembg
from typing import Any
import json
import os
import json
import argparse

from model import CRM
from inference import generate3d

pipeline = None
rembg_session = rembg.new_session()


def expand_to_square(image, bg_color=(0, 0, 0, 0)):
    # expand image to 1:1
    width, height = image.size
    if width == height:
        return image
    new_size = (max(width, height), max(width, height))
    new_image = Image.new("RGBA", new_size, bg_color)
    paste_position = ((new_size[0] - width) // 2, (new_size[1] - height) // 2)
    new_image.paste(image, paste_position)
    return new_image

def check_input_image(input_image):
    if input_image is None:
        raise gr.Error("No image uploaded!")


def remove_background(
    image: PIL.Image.Image,
    rembg_session: Any = None,
    force: bool = False,
    **rembg_kwargs,
) -> PIL.Image.Image:
    do_remove = True
    if image.mode == "RGBA" and image.getextrema()[3][0] < 255:
        # explain why current do not rm bg
        print("alhpa channl not enpty, skip remove background, using alpha channel as mask")
        background = Image.new("RGBA", image.size, (0, 0, 0, 0))
        image = Image.alpha_composite(background, image)
        do_remove = False
    do_remove = do_remove or force
    if do_remove:
        image = rembg.remove(image, session=rembg_session, **rembg_kwargs)
    return image

def do_resize_content(original_image: Image, scale_rate):
    # resize image content wile retain the original image size
    if scale_rate != 1:
        # Calculate the new size after rescaling
        new_size = tuple(int(dim * scale_rate) for dim in original_image.size)
        # Resize the image while maintaining the aspect ratio
        resized_image = original_image.resize(new_size)
        # Create a new image with the original size and black background
        padded_image = Image.new("RGBA", original_image.size, (0, 0, 0, 0))
        paste_position = ((original_image.width - resized_image.width) // 2, (original_image.height - resized_image.height) // 2)
        padded_image.paste(resized_image, paste_position)
        return padded_image
    else:
        return original_image

def add_background(image, bg_color=(255, 255, 255)):
    # given an RGBA image, alpha channel is used as mask to add background color
    background = Image.new("RGBA", image.size, bg_color)
    return Image.alpha_composite(background, image)


def preprocess_image(image, background_choice, foreground_ratio, backgroud_color):
    """
    input image is a pil image in RGBA, return RGB image
    """
    print(background_choice)
    if background_choice == "Alpha as mask":
        background = Image.new("RGBA", image.size, (0, 0, 0, 0))
        image = Image.alpha_composite(background, image)
    else:
        image = remove_background(image, rembg_session, force_remove=True)
    image = do_resize_content(image, foreground_ratio)
    image = expand_to_square(image)
    image = add_background(image, backgroud_color)
    return image.convert("RGB")


def gen_image(input_image, seed, scale, step):
    global pipeline, model, args
    pipeline.set_seed(seed)
    rt_dict = pipeline(input_image, scale=scale, step=step)
    stage1_images = rt_dict["stage1_images"]
    stage2_images = rt_dict["stage2_images"]
    np_imgs = np.concatenate(stage1_images, 1)
    np_xyzs = np.concatenate(stage2_images, 1)

    glb_path, obj_path = generate3d(model, np_imgs, np_xyzs, args.device)
    return Image.fromarray(np_imgs), Image.fromarray(np_xyzs), glb_path, obj_path


parser = argparse.ArgumentParser()
parser.add_argument(
    "--stage1_config",
    type=str,
    default="configs/nf7_v3_SNR_rd_size_stroke.yaml",
    help="config for stage1",
)
parser.add_argument(
    "--stage2_config",
    type=str,
    default="configs/stage2-v2-snr.yaml",
    help="config for stage2",
)

parser.add_argument("--device", type=str, default="cuda")
args = parser.parse_args()

#crm_path = hf_hub_download(repo_id="Zhengyi/CRM", filename="CRM.pth")
crm_path = '.../CRM.pth'
specs = json.load(open("configs/specs_objaverse_total.json"))
model = CRM(specs).to(args.device)
model.load_state_dict(torch.load(crm_path, map_location = args.device), strict=False)

stage1_config = OmegaConf.load(args.stage1_config).config
stage2_config = OmegaConf.load(args.stage2_config).config
stage2_sampler_config = stage2_config.sampler
stage1_sampler_config = stage1_config.sampler

stage1_model_config = stage1_config.models
stage2_model_config = stage2_config.models

#xyz_path = hf_hub_download(repo_id="Zhengyi/CRM", filename="ccm-diffusion.pth")
#pixel_path = hf_hub_download(repo_id="Zhengyi/CRM", filename="pixel-diffusion.pth")
xyz_path = '.../ccm-diffusion.pth' 
pixel_path = '.../pixel-diffusion.pth'
stage1_model_config.resume = xyz_path
stage2_model_config.resume = pixel_path

pipeline = TwoStagePipeline(
    stage1_model_config,
    stage2_model_config,
    stage1_sampler_config,
    stage2_sampler_config,
    device=args.device,
    dtype=torch.float16
)


image_path = '.../demo_img.png'
image_input = PIL.Image.open(image_path)
preprocessed_image = preprocess_image(image_input, "Alpha as mask", 1.0, "#7F7F7F")

novel_views, ccms, glb_path, obj_path = gen_image(preprocessed_image, 1234, 0.55, 30)
```

I didn't modify the codes too much actually. 
Thanks

**Comment by thuwzy** [comment]
The code
```
stage1_model_config.resume = xyz_path
stage2_model_config.resume = pixel_path
```
should be changed into the following code?
```
stage1_model_config.resume = pixel_path
stage2_model_config.resume = xyz_path
```

**Comment by tiangexiang** [comment]
Thanks for your reply! Interesting, so the checkpoints do need to be swapped. Although the models can be loaded in this way, but I cannot get same output quality as the ones from HF gradio. Do you have any suggestions?

**Comment by thuwzy** [comment]
Can I see your your 3D result? Also, pixel diffusion is for stage1 and xyz diffusion is for stage2. There is no swap.

**Comment by tiangexiang** [comment]
I have tried two separate runs and got very different novel view generation results:
![novel_views](https://github.com/thu-ml/CRM/assets/67831103/f5412812-9fc4-44eb-a847-d3ae55091ce9)
![novel_views2](https://github.com/thu-ml/CRM/assets/67831103/28b5a239-a79d-4121-99ff-fd0e58d3fa8c)

**Comment by thuwzy** [comment]
The last colume is your input image? I think the problem results from the unclean background? We assume that the input image is correctly pre-processed into a grey background, otherwise the results will be unpredictable.

**Comment by tiangexiang** [comment]
Oh not exactly, here is the preprocessed image:
![preprocessed](https://github.com/thu-ml/CRM/assets/67831103/14a0a153-dd30-4ba5-bcab-d8ce632de91f)
So you are suggesting the preprocessed image may be wrongly passed to the generation pipeline? Thanks!

**Comment by thuwzy** [comment]
Yes, the preprocessed image may be wrongly passed to the generation pipeline. The last image should be exactly the same as the preprocessed image.
